### ISSUE TITLE
Logging Errors

### ISSUE THREAD

**Issue by sglover** [accanto-systems/ignition#29]
Errors like this are appearing in the logs:

```
--- Logging error ---
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/logging/__init__.py", line 1025, in emit
    msg = self.format(record)
  File "/usr/local/lib/python3.7/logging/__init__.py", line 869, in format
    return fmt.format(record)
  File "/usr/local/lib/python3.7/site-packages/ignition/service/logging.py", line 136, in format
    return self.serialize(message)
  File "/usr/local/lib/python3.7/site-packages/ignition/service/logging.py", line 110, in serialize
    return json.dumps(message)
  File "/usr/local/lib/python3.7/json/__init__.py", line 231, in dumps
    return _default_encoder.encode(obj)
  File "/usr/local/lib/python3.7/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/usr/local/lib/python3.7/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "/usr/local/lib/python3.7/json/encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type type is not JSON serializable
Call stack:
  File "/usr/local/lib/python3.7/site-packages/kopdriver/__init__.py", line 12, in create_wsgi_app
    ignition_app = create_app()
  File "/usr/local/lib/python3.7/site-packages/kopdriver/app.py", line 39, in create_app
    return app_builder.configure()
  File "/usr/local/lib/python3.7/site-packages/ignition/boot/api.py", line 127, in configure
    return BootstrapRunner(configuration).init_app()
  File "/usr/local/lib/python3.7/site-packages/ignition/boot/app.py", line 149, in init_app
    connexion_app.add_api(connexion_api['api_spec'], **connexion_api['kwargs'])
  File "/usr/local/lib/python3.7/site-packages/connexion/apps/flask_app.py", line 54, in add_api
    api = super(FlaskApp, self).add_api(specification, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/connexion/apps/abstract.py", line 155, in add_api
    options=api_options.as_dict())
  File "/usr/local/lib/python3.7/site-packages/connexion/apis/abstract.py", line 109, in __init__
    self.add_paths()
  File "/usr/local/lib/python3.7/site-packages/connexion/apis/abstract.py", line 207, in add_paths
    self.add_operation(path, method)
  File "/usr/local/lib/python3.7/site-packages/connexion/apis/abstract.py", line 173, in add_operation
    self._add_operation_internal(method, path, operation)
  File "/usr/local/lib/python3.7/site-packages/connexion/apis/flask_api.py", line 106, in _add_operation_internal
    function = operation.function
  File "/usr/local/lib/python3.7/site-packages/connexion/operations/abstract.py", line 370, in function
    security_decorator = self.security_decorator
  File "/usr/local/lib/python3.7/site-packages/connexion/operations/secure.py", line 75, in security_decorator
    logger.debug('... Security: %s', self.security, extra=vars(self))
```

**Comment by sglover** [comment]
This appears to be the https://github.com/accanto-systems/ignition/blob/aa30e0dea546e8c6a89865e4b723e023b3f65f6e/ignition/service/logging.py#L56 method adding JSON-incompatible data to the JSON log message. There are a couple of options:

* remove "type(None)" from the list of "python_types"
* whitelist fields to add rather than blacklist fields to not add
